### ISSUE TITLE
在其他数据集上训练

### ISSUE THREAD

**Issue by WYL211** [OSUPCVLab/SegFormer3D#15]
感谢您的工作；您如何在自动心脏诊断数据集 (ACDC) 和多器官 CT 分割数据集 (Synapse) 上进行训练？您能为我提供数据加载器的代码吗？我将不胜感激。

**Comment by bnavard** [comment]
Since I cannot read Chinese I am rewriting the question so that everyone understands. I used google translate:

"Thanks for your work; how did you train on the Automatic Cardiac Diagnosis Dataset (ACDC) and the Multi-Organ CT Segmentation Dataset (Synapse)? Can you provide me the code for the data loader? I would be grateful for any help."
